# Generated by Django 2.1.7 on 2019-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goodsNum', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goodsPrice', models.IntegerField(default=0, verbose_name='商品价格')),
                ('goodsSpecId', models.CharField(max_length=200, verbose_name='商品规格')),
                ('goodsImg', models.CharField(max_length=200, verbose_name='商品图')),
            ],
        ),
    ]
