# Generated by Django 2.1.7 on 2019-03-19 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(help_text='商品名称', max_length=50, verbose_name='商品名称')),
                ('goodsNum', models.IntegerField(default=0, help_text='商品库存', verbose_name='商品库存')),
                ('goodsPrice', models.IntegerField(default=0, help_text='商品价格', verbose_name='商品价格')),
                ('goodsSpecId', models.CharField(help_text='商品规格', max_length=200, verbose_name='商品规格')),
                ('goodsImg', models.ImageField(blank=True, help_text='商品图', max_length=200, null=True, upload_to='goods/', verbose_name='商品图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='品牌名称')),
                ('desc', models.TextField(default='', max_length=200, verbose_name='品牌描述')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='brand/', verbose_name='品牌LOGO')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('brands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_good', to='goods.GoodBrand', verbose_name='品牌')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_good', to='goods.Good', verbose_name='商品名称')),
            ],
            options={
                'verbose_name': '上架',
                'verbose_name_plural': '上架',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='brands',
            field=models.ForeignKey(blank=True, help_text='品牌', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodBrand', verbose_name='品牌'),
        ),
    ]
