# Generated by Django 2.1.7 on 2019-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190315_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodbrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brand/', verbose_name='品牌LOGO'),
        ),
    ]
