# Generated by Django 2.1.7 on 2019-03-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190315_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='brands',
        ),
        migrations.AddField(
            model_name='goodbrand',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='goods.Good', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsImg',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='goods/', verbose_name='商品图'),
        ),
        migrations.AlterField(
            model_name='goodbrand',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='brand/', verbose_name='品牌LOGO'),
        ),
    ]
