# Generated by Django 2.1.7 on 2019-03-15 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190315_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('brands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_good', to='goods.GoodBrand', verbose_name='品牌')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_good', to='goods.Good', verbose_name='商品名称')),
            ],
            options={
                'verbose_name': '创建商品',
                'verbose_name_plural': '创建商品',
            },
        ),
    ]
