# Generated by Django 2.1.7 on 2019-03-19 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_goodinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodinfo',
            options={'verbose_name': '上架', 'verbose_name_plural': '上架'},
        ),
        migrations.AlterField(
            model_name='good',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='good',
            name='brands',
            field=models.ForeignKey(blank=True, help_text='品牌', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodBrand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsImg',
            field=models.ImageField(blank=True, help_text='商品图', max_length=200, null=True, upload_to='goods/', verbose_name='商品图'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsName',
            field=models.CharField(help_text='商品名称', max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsNum',
            field=models.IntegerField(default=0, help_text='商品库存', verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsPrice',
            field=models.IntegerField(default=0, help_text='商品价格', verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsSpecId',
            field=models.CharField(help_text='商品规格', max_length=200, verbose_name='商品规格'),
        ),
    ]
